[theme]
name = "Cyberpunk Purple"

[ui]
font-family =""
font-size = 12
header-height = 35
status-height = 25
tab-min-width = 100
scroll-width = 10
drop-shadow-width = 0
custom-titlebar = false
hover-font-family = ""
hover-font-size = 0

[theme.base]
white = "#ABB2BF"
black = "#282C34"
grey = "#3E4451"
blue = "#61AFEF"
red = "#E06C75"
yellow = "#E5C07B"
orange = "#D19A66"
green = "#98C379"
purple = "#C678DD"
cyan = "#56B6C2"
magenta = "#C678DD"

#This syntax is what was forked, credit to MinusGix/lapce-aleph
[theme.syntax]
"comment" = "#5C6370"
"constant" = "#D62C2C"
"type" = "#A95EFF"
"typeAlias" = "#b079ee"
"number" = "$yellow"
"enum" = "#9263D3"
"enumMember" = "#AA63D3"
"struct" = "#A95EFF"
"structure" = "#A95EFF"
"attribute" = "$orange"
"constructor" = "$yellow"
"variable" = "#FF478D"
"macro" = "#28A9FF"
"operator" = "#EEEEEE60"
"variable.parameter" = "#FF478D"
"selfKeyword" = "#14E5D4"
"property" = "#FF7135"
"interface" = "#DD46C2"
"function" = "$blue"
"method" = "#28A9FF"
"function.method" = "$blue"
"keyword" = "#14E5D4"
"field" = "$red"
"enum-member" = "$red"
# "style.variable.other.member" = "$red"
"string" = "$green"
"type.builtin" = "$cyan"
"builtinType" = "$cyan"
"escape" = "$cyan"
"embedded" = "$cyan"

[theme.ui]
"activity.background" = "#1f0430"
"activity.current" = "#560b85"
"completion.background" = "#1f0430"
"completion.current" = "#560b85"
"editor.background" = "#1f0430"
"editor.caret" = "#f30cdc"
"editor.current_line" = "#5F005F"
"editor.dim" = "#5C6370"
"editor.focus" = "#CCCCCC"
"editor.foreground" = "#d6bacd"
"editor.link" = "$cyan"
"editor.selection" = "#560b85"
"hover.background" = "#1f0430"
"inlay_hint.background" = "#1f0430"
"inlay_hint.foreground" = "#d6bacd"
"lapce.active_tab" = "$black"
"lapce.border" = "#560b85"
"lapce.dropdown_shadow" = "#000000"
"lapce.error" = "$red"
"lapce.inactive_tab" = "$grey"
"lapce.scroll_bar" = "$grey"
"lapce.warn" = "$yellow"
"markdown.blockquote" = "#898989"
"palette.background" = "#1f0430"
"palette.current" = "#560b85"
"panel.background" = "#1f0430"
"panel.current" = "#560b85"
"panel.hovered" = "#5F005F"
"source_control.added" = "#50A14F32"
"source_control.modified" = "#0184BC32"
"source_control.removed" = "#FF526632"
"status.background" = "#1f0430"
"status.modal.insert" = "$red"
"status.modal.normal" = "$blue"
"status.modal.terminal" = "$purple"
"status.modal.visual" = "$yellow"
"terminal.background" = "#1F0430"
"terminal.black" = "$black"
"terminal.bright_black" = "#545862"
"terminal.bright_blue" = "$blue"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_green" = "$green"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_red" = "$red"
"terminal.bright_white" = "#C8CCD4"
"terminal.bright_yellow" = "$yellow"
"terminal.cursor" = "$white"
"terminal.cyan" = "$cyan"
"terminal.foreground" = "#d6bacd"
"terminal.green" = "$green"
"terminal.magenta" = "$magenta"
"terminal.red" = "$red"
"terminal.white" = "$white"
"terminal.yellow" = "$yellow"
