name = "cyberpunk-purple"
display-name = "Cyberpunk Purple"
description = "Colourful Purple Cyberpunk Theme"
version = "0.0.1"
author = "DEFCON001"
repository = "DEFCON001/lapce-cyberpunk-purple"
themes = ["cyberpunk-purple.toml"]
